---
- name: install | create group
  group:
    name: "{{ consul_group }}"
    system: yes

- name: install | create user
  user:
    name: "{{ consul_user }}"
    group: "{{ consul_group }}"
    groups: "{{ consul_groups|join(',') }}"
    system: yes

- name: install | create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    recurse: yes
  with_items:
    - "{{ consul_data_dir }}"
    - "{{ consul_config_dir }}"
    - "{{ consul_ui_dir }}"

- name: install | utils
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 86400
  with_items:
    - unzip
    - python-setuptools

- name: install | install python-consul
  easy_install:
    name: python-consul

- name: install | download
  get_url:
    url: "{{ consul_download }}"
    dest: /tmp
  register: consul_download_result

- name: install | unarchive
  unarchive:
    src: "/tmp/{{ consul_archive }}"
    dest: /bin
    copy: no
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
  when: consul_download_result.changed

- name: install | create UI directory
  file:
    path: "{{ consul_ui_dir }}"
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"

- name: install | download consul ui
  get_url:
    url: "{{ consul_ui_download }}"
    dest: /tmp
  register: consul_ui_was_downloaded
  when: consul_server|bool

- name: install | copy and unpack consul ui
  unarchive:
    src: "/tmp/{{ consul_ui_archive }}"
    dest: "{{ consul_ui_dir }}"
    copy: no
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
  when: consul_ui_was_downloaded.changed
