---
- name: install | utils
  apt: name={{ item }} update_cache=yes cache_valid_time=86400
  with_items:
    - unzip
    - python-setuptools

- name: install | install python-consul
  easy_install: name=python-consul

- name: install | download
  get_url: url={{ consul_download }} dest=/tmp sha256sum={{ consul_archive_sha256sum }}
  register: consul_was_downloaded

- name: install | unarchive
  unarchive: src=/tmp/{{ consul_archive }} dest=/bin copy=no
  when: consul_was_downloaded.changed

- name: install | create user
  user: name={{ consul_user }} groups={{ consul_user_groups | join(',') }} system=yes

- name: install | create directories
  file: >
    path={{ item }} state=directory
    owner={{ consul_user }} group={{ consul_user }}
    recurse=true
  with_items:
    - "{{ consul_data_dir }}"
    - "{{ consul_config_dir }}"

- name: install | create ui directory
  file: >
    path={{ consul_ui_dir }} state=directory
    owner={{ consul_user }} group={{ consul_user }}
    recurse=true
  changed_when: False

- name: install | download consul ui
  get_url: url={{ consul_ui_download }}  dest=/tmp sha256sum={{ consul_ui_archive_sha256sum }}
  register: consul_ui_was_downloaded

- name: install | copy and unpack consul ui
  unarchive: src=/tmp/{{ consul_ui_archive }} dest=/var/consul/ui copy=no
  when: consul_ui_was_downloaded.changed

- name: install | render config
  template: >
    src=consul.json dest={{ consul_config_dir }}/consul.json
    owner={{ consul_user }} group={{ consul_user }}
  notify: reload consul

- name: install | render upstart configs
  template: src=upstart.conf dest=/etc/init/{{ consul_service_name }}.conf

- name: install | enable service
  service: name={{ consul_service_name }} enabled=yes state=started
