# -*- mode: ruby -*-
# vi: set ft=ruby :

address_prefix = ENV['ADDRESS_PREFIX'] || "192.168.77.2"
server_count = (ENV['SERVER_COUNT'] || 3).to_i
server_addresses = []

Vagrant.configure("2") do |config|
  config.vm.box = "phusion/ubuntu-14.04-amd64"

  (1..server_count).each do |machine_id|
    config.vm.define "machine#{machine_id}" do |machine|
      server_addresses << "#{address_prefix}#{machine_id}"

      machine.vm.hostname = "machine#{machine_id}"
      machine.vm.network "private_network", ip: server_addresses.last

      if machine_id == server_count

        machine.vm.provision :ansible do |ansible|
          ansible.limit = "all"
          ansible.verbose = true
          ansible.playbook = "test.yml"
          ansible.extra_vars = {
            role_name: Dir.pwd.split('/')[-2],
            consul_start_join: server_addresses
          }
        end

      end

    end

  end

end
